### ISSUE TITLE
build is not working: ../../src/module.h:344:10: fatal error: module_strings.h: No such file or directory

### ISSUE THREAD

**Issue by holywen** [petabyt/mlt#1]
root@ML:~/magic-lantern-branch-unified/modules/mlt# make
Generating files...
Formatting...
Using /usr/bin/arm-none-eabi-gcc (from PATH).
abort: no repository found in '/root/magic-lantern-branch-unified/modules/mlt' (.hg not found)
abort: no repository found in '/root/magic-lantern-branch-unified/modules/mlt' (.hg not found)
[ README   ]   module_strings.h
sh ../last_change_info.sh

abort: no repository found in '/root/magic-lantern-branch-unified/modules/mlt' (.hg not found)

(<type 'exceptions.SystemExit'>, SystemExit(1,), <traceback object at 0x7fb49b68deb0>)
[ CC       ]   mlt.o
In file included from mlt.c:6:
../../src/module.h:344:10: fatal error: module_strings.h: No such file or directory
  344 | #include "module_strings.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [../../Makefile.filerules:21: mlt.o] Error 1

**Comment by petabyt** [comment]
That's a problem with ML build system, you need to install all the packages required in order to build both ML and mlt
It's late for me, but I think it's something you have to install with pip2

**Comment by holywen** [comment]
Looks like it's  still checking the latest change info with hg command:
readme2modulestrings.py
-------------------------------------------------------

```
last_change_info = run("sh ../last_change_info.sh")

if len(last_change_info):
    last_change_date, last_changeset, author, commit_msg = last_change_info.split("\n")
    split = last_change_date.split(" ")
    seconds = float(split[0])
    last_change_date = datetime.utcfromtimestamp(seconds).strftime("%Y-%m-%d %H:%M:%S UTC")
```

cat last_change_info.sh

```
#!/bin/sh

# Called from readme2modulestrings.py
# also useful by itself to look at a formatted report
# of the extracted version info

LC_TIME=EN \
hg log . -r 'reverse(ancestors(.))' -l 1 --template \
'{date|hgdate}\n{node|short}\n{author|user}\n{desc|strip|firstline}'
```

**Comment by holywen** [comment]
Do you also host this repo in some hg server as well?
if so maybe I can use that one so hg command will not fail.

**Comment by holywen** [comment]
Now I got a different error after providing some dummy text in the last_change_info.sh

```
root@ML:~/magic-lantern-branch-unified/modules/mlt# make
Generating files...
Formatting...
Using /usr/bin/arm-none-eabi-gcc (from PATH).
abort: no repository found in '/root/magic-lantern-branch-unified/modules/mlt' (.hg not found)
abort: no repository found in '/root/magic-lantern-branch-unified/modules/mlt' (.hg not found)
[ CC       ]   mlt.o
mlt.c:7:10: fatal error: patch.h: No such file or directory
    7 | #include <patch.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [../../Makefile.filerules:21: mlt.o] Error 1
```

**Comment by holywen** [comment]
FYI: I got the magic lantern unified branch from: https://foss.heptapod.net/magic-lantern/magic-lantern

**Comment by holywen** [comment]
it works now after I got the ML code from: https://github.com/ccritix/magic-lantern
