### ISSUE TITLE
Error loading on 5d3 nightly build:  undefined symbol: 'patch_hook_function'

### ISSUE THREAD

**Issue by holywen** [petabyt/mlt#2]
the ML version is: https://builds.magiclantern.fm/5D3-123.html
download URL:
https://builds.magiclantern.fm/jenkins/job/5D3.123/83/artifact/platform/5D3.123/magiclantern-Nightly.2018Jul03.5D3123.zip

undefined symbol: 'patch_hook_function'

![mlt_error](https://github.com/petabyt/mlt/assets/3616302/b69f60c6-ef71-42ff-90c9-c9221135a4e3)

Looks like there is no 'patch_hook_function' in the latest ML firmware anymore?

**Comment by holywen** [comment]
OK I figured it out that https://github.com/reticulatedpines/magiclantern_simplified is working and I can build the whole firmware and together with mlt module.
Will try to use that build and try mlt again.

```
make 5D3.123_zip
```
works for me.

**Comment by holywen** [comment]
Hi I tried to use this build and also with the mlt module, unfortunately it's not working: what ever language I choose, it always shows English in the UI.

**Comment by petabyt** [comment]
There's a setting to change the language

**Comment by petabyt** [comment]
This module really needs a rewrite, so it will probably be merged in the simplified repo when that happens

**Comment by petabyt** [comment]
Last time I checked i think it worked, but I'm sure there's bugs
