### ISSUE TITLE
The ML code base that this module works 

### ISSUE THREAD

**Issue by holywen** [petabyt/mlt#3]
Could you please kindly share which code base of the ML works best for this module?

I would like to make it to support Chinese language.
Thanks a lot.

**Comment by petabyt** [comment]
I barely got Chinese rendering about 2 years ago, and it barely worked back then. It really just needs a complete rewrite.

It should work with the most recent ML builds. But again, it's been around 2 years since I last tested it.

**Comment by petabyt** [comment]
Also the Chinese font, even at the lowest resolution, took way too much RAM. I think it took almost all that was allocated.

**Comment by holywen** [comment]
Thanks a lot for your information.

**Comment by petabyt** [comment]
You could maybe just store every string as a bitmap, that could potentially take a lot less memory. But IRRC Chinese pixel font took around 600k RAM. ML has about 2mb.

You could also remove any Chinese characters that isn't used. I'm not familiar with Chinese but I think ML is probably using 1% of the available characters.
